runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /index\.html
  static_files: index.html
  upload: index.html
  secure: always